### ISSUE TITLE
feat: create lib to handle file upload for Fastify-based apps

### ISSUE THREAD

**Issue by getlarge** [getlarge/nestjs-tools#71]
To solve this issue some solutions already exist:
- [@nest-lab/fastify-multer](https://github.com/jmcdo29/nest-lab/tree/main/packages/fastify-multer) developed by one of the NestJS core team members
- [nest-file-fastify](https://github.com/Blazity/nest-file-fastify/tree/master)

`@nest-lab/fastify-multer` depends on [fastify-multer](https://github.com/fox1t/fastify-multer), which is abandoned and not maintained anymore ❌

`nest-file-fastify` depends on [fastify-multipart](https://github.com/fastify/fastify-multipart), and the Fastify team maintains it. But nest-file-fastify is [outdated and unmaintened](https://github.com/Blazity/nest-file-fastify/pull/8). ❌

This lib will fork `nest-file-fastify` and update the `fastify-multipart` dependency to the latest version.

**Comment by JoCat** [comment]
👍
